### ISSUE TITLE
Expand weather tracking feature

### ISSUE THREAD

**Issue by tmhntr** [tmhntr/tauri-migraine-log#4]
- [ ] add weather api integration
- [ ] expand weather data type and 
- [ ] (?) implement daily weather logging
