### ISSUE TITLE
Add treatment tracking feature

### ISSUE THREAD

**Issue by tmhntr** [tmhntr/tauri-migraine-log#6]
- [ ] add management table to db
- [ ] add management tracker to home page
- [ ] add managements to entry adder
